<?php

/**
 * BaseCommunityList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property boolean $featured
 * @property integer $submitted_by
 * @property sfGuardUser $User
 * @property Doctrine_Collection $Items
 * 
 * @method string              getTitle()        Returns the current record's "title" value
 * @method string              getDescription()  Returns the current record's "description" value
 * @method boolean             getFeatured()     Returns the current record's "featured" value
 * @method integer             getSubmittedBy()  Returns the current record's "submitted_by" value
 * @method sfGuardUser         getUser()         Returns the current record's "User" value
 * @method Doctrine_Collection getItems()        Returns the current record's "Items" collection
 * @method CommunityList       setTitle()        Sets the current record's "title" value
 * @method CommunityList       setDescription()  Sets the current record's "description" value
 * @method CommunityList       setFeatured()     Sets the current record's "featured" value
 * @method CommunityList       setSubmittedBy()  Sets the current record's "submitted_by" value
 * @method CommunityList       setUser()         Sets the current record's "User" value
 * @method CommunityList       setItems()        Sets the current record's "Items" collection
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseCommunityList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('community_list');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('featured', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('submitted_by', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'submitted_by',
             'foreign' => 'id'));

        $this->hasMany('CommunityListItem as Items', array(
             'local' => 'id',
             'foreign' => 'list_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $markdown0 = new Doctrine_Template_Markdown(array(
             'fields' => 
             array(
              0 => 'description',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
        $this->actAs($markdown0);
    }
}