<?php

/**
 * BaseCommunityList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property boolean $featured
 * @property integer $submitted_by
 * @property sfGuardUser $User
 * @property Doctrine_Collection $Items
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6365 2009-09-15 18:22:38Z jwage $
 */
abstract class BaseCommunityList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('community_list');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('featured', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('submitted_by', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('sfGuardUser as User', array(
             'local' => 'submitted_by',
             'foreign' => 'id'));

        $this->hasMany('CommunityListItem as Items', array(
             'local' => 'id',
             'foreign' => 'list_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $markdown0 = new Doctrine_Template_Markdown(array(
             'fields' => 
             array(
              0 => 'description',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
        $this->actAs($markdown0);
    }
}