<?php

/**
 * BaseSymfonyApiVersion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $PluginRelease
 * @property Doctrine_Collection $PluginReleaseSymfonyApiVersion
 * 
 * @method string              getName()                           Returns the current record's "name" value
 * @method Doctrine_Collection getPluginRelease()                  Returns the current record's "PluginRelease" collection
 * @method Doctrine_Collection getPluginReleaseSymfonyApiVersion() Returns the current record's "PluginReleaseSymfonyApiVersion" collection
 * @method SymfonyApiVersion   setName()                           Sets the current record's "name" value
 * @method SymfonyApiVersion   setPluginRelease()                  Sets the current record's "PluginRelease" collection
 * @method SymfonyApiVersion   setPluginReleaseSymfonyApiVersion() Sets the current record's "PluginReleaseSymfonyApiVersion" collection
 * 
 * @package    plugintracker
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSymfonyApiVersion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('symfony_api_version');
        $this->hasColumn('name', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PluginRelease', array(
             'refClass' => 'PluginReleaseSymfonyApiVersion',
             'local' => 'api_version_id',
             'foreign' => 'release_id'));

        $this->hasMany('PluginReleaseSymfonyApiVersion', array(
             'local' => 'id',
             'foreign' => 'api_version_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}