<?php

/**
 * BasePluginRating
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $symfony_plugin_id
 * @property integer $sf_guard_user_id
 * @property integer $rating
 * @property SymfonyPlugin $Plugin
 * @property sfGuardUser $User
 * 
 * @method integer       getSymfonyPluginId()   Returns the current record's "symfony_plugin_id" value
 * @method integer       getSfGuardUserId()     Returns the current record's "sf_guard_user_id" value
 * @method integer       getRating()            Returns the current record's "rating" value
 * @method SymfonyPlugin getPlugin()            Returns the current record's "Plugin" value
 * @method sfGuardUser   getUser()              Returns the current record's "User" value
 * @method PluginRating  setSymfonyPluginId()   Sets the current record's "symfony_plugin_id" value
 * @method PluginRating  setSfGuardUserId()     Sets the current record's "sf_guard_user_id" value
 * @method PluginRating  setRating()            Sets the current record's "rating" value
 * @method PluginRating  setPlugin()            Sets the current record's "Plugin" value
 * @method PluginRating  setUser()              Sets the current record's "User" value
 * 
 * @package    plugintracker
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePluginRating extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('plugin_rating');
        $this->hasColumn('symfony_plugin_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('rating', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SymfonyPlugin as Plugin', array(
             'local' => 'symfony_plugin_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}