<?php

/**
 * BaseCommunityListItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $body
 * @property integer $list_id
 * @property integer $score
 * @property integer $count
 * @property integer $submitted_by
 * @property CommunityList $List
 * @property sfGuardUser $User
 * 
 * @method string            getTitle()        Returns the current record's "title" value
 * @method clob              getBody()         Returns the current record's "body" value
 * @method integer           getListId()       Returns the current record's "list_id" value
 * @method integer           getScore()        Returns the current record's "score" value
 * @method integer           getCount()        Returns the current record's "count" value
 * @method integer           getSubmittedBy()  Returns the current record's "submitted_by" value
 * @method CommunityList     getList()         Returns the current record's "List" value
 * @method sfGuardUser       getUser()         Returns the current record's "User" value
 * @method CommunityListItem setTitle()        Sets the current record's "title" value
 * @method CommunityListItem setBody()         Sets the current record's "body" value
 * @method CommunityListItem setListId()       Sets the current record's "list_id" value
 * @method CommunityListItem setScore()        Sets the current record's "score" value
 * @method CommunityListItem setCount()        Sets the current record's "count" value
 * @method CommunityListItem setSubmittedBy()  Sets the current record's "submitted_by" value
 * @method CommunityListItem setList()         Sets the current record's "List" value
 * @method CommunityListItem setUser()         Sets the current record's "User" value
 * 
 * @package    plugintracker
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCommunityListItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('community_list_item');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('list_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('score', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('count', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('submitted_by', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CommunityList as List', array(
             'local' => 'list_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'submitted_by',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $markdown0 = new Doctrine_Template_Markdown(array(
             'fields' => 
             array(
              0 => 'body',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($markdown0);
    }
}