<?php

/**
 * BasePluginCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $description
 * @property Doctrine_Collection $Plugins
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method clob                getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getPlugins()     Returns the current record's "Plugins" collection
 * @method PluginCategory      setName()        Sets the current record's "name" value
 * @method PluginCategory      setDescription() Sets the current record's "description" value
 * @method PluginCategory      setPlugins()     Sets the current record's "Plugins" collection
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BasePluginCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('plugin_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SymfonyPlugin as Plugins', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($sluggable0);
    }
}