<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePluginRating extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('plugin_rating');
        $this->hasColumn('symfony_plugin_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('rating', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        $this->hasOne('SymfonyPlugin as Plugin', array(
             'local' => 'symfony_plugin_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}