<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePluginRelease extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('plugin_release');
        $this->hasColumn('plugin_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('version', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('symfony_version_min', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('symfony_version_max', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('summary', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('stability', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('readme', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('dependencies', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        $this->hasOne('SymfonyPlugin as Plugin', array(
             'local' => 'plugin_id',
             'foreign' => 'id'));
    }
}