<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCommunityList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('community_list');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('featured', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('submitted_by', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
    }

    public function setUp()
    {
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'submitted_by',
             'foreign' => 'id'));

        $this->hasMany('CommunityListItem as Items', array(
             'local' => 'id',
             'foreign' => 'list_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $markdown0 = new Doctrine_Template_Markdown(array(
             'fields' => 
             array(
              0 => 'description',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
        $this->actAs($markdown0);
    }
}