<?php

/**
 * BaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $description
 * @property Doctrine_Collection $PluginTags
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method clob                getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getPluginTags()  Returns the current record's "PluginTags" collection
 * @method Tag                 setName()        Sets the current record's "name" value
 * @method Tag                 setDescription() Sets the current record's "description" value
 * @method Tag                 setPluginTags()  Sets the current record's "PluginTags" collection
 * 
 * @package    plugintracker
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PluginTag as PluginTags', array(
             'local' => 'id',
             'foreign' => 'tag_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}