<?php

/**
 * BasePluginReleaseDependency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $release_id
 * @property integer $dependency_id
 * @property string $dependency_version_min
 * @property string $dependency_version_max
 * @property PluginRelease $Release
 * @property SymfonyPlugin $Dependency
 * 
 * @method integer                 getReleaseId()              Returns the current record's "release_id" value
 * @method integer                 getDependencyId()           Returns the current record's "dependency_id" value
 * @method string                  getDependencyVersionMin()   Returns the current record's "dependency_version_min" value
 * @method string                  getDependencyVersionMax()   Returns the current record's "dependency_version_max" value
 * @method PluginRelease           getRelease()                Returns the current record's "Release" value
 * @method SymfonyPlugin           getDependency()             Returns the current record's "Dependency" value
 * @method PluginReleaseDependency setReleaseId()              Sets the current record's "release_id" value
 * @method PluginReleaseDependency setDependencyId()           Sets the current record's "dependency_id" value
 * @method PluginReleaseDependency setDependencyVersionMin()   Sets the current record's "dependency_version_min" value
 * @method PluginReleaseDependency setDependencyVersionMax()   Sets the current record's "dependency_version_max" value
 * @method PluginReleaseDependency setRelease()                Sets the current record's "Release" value
 * @method PluginReleaseDependency setDependency()             Sets the current record's "Dependency" value
 * 
 * @package    plugintracker
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePluginReleaseDependency extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('plugin_release_dependency');
        $this->hasColumn('release_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('dependency_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('dependency_version_min', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('dependency_version_max', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PluginRelease as Release', array(
             'local' => 'release_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('SymfonyPlugin as Dependency', array(
             'local' => 'dependency_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}