<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugincsNavigationItemTable extends Doctrine_Table
{
  // Queries to find if there are any navigation 
  // records in the database
  public function isPopulated()
  {
    return ($this->createQuery()->count() > 1);
  }
  
  public function getNavigationRoot()
  {
    return $this->createQuery()->where('level = ?', 0)->fetchOne();
  }
}