<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugincsNavigationMenuTable extends Doctrine_Table
{
  protected $_tree;
  
  public function configure()
  {
   // Extend this class here to dynamically add branches to your tree using
   // the appendItem() method.  These results will be cached, so you must 
   // implement cache clearing in your code:

   /*
   $cachePath = sfConfig::get('sf_cache_dir').'/navigation_tree.cache';
   if (file_exists($cachePath)) 
   {
     unlink($cachePath);
   }
   */
  }
  
  public function storeTree($tree)
  {
    $this->_tree = $tree;
  }
  
  public function restoreTree()
  {
    return $this->_tree;
  }
  
  public function getMenu($name = null)
  {
    if ($name == null) 
    {
      return $this->_tree[0];
    }
    foreach ($this->_tree as $menu) 
    {
      if ($menu->title == $name) 
      {
        return $menu;
      }
    }
    return null;
  }
}