<?php
// auto-generated by csNavigationConfigHandler
// date: 2009-11-13 16:16:33
$navigation = array(
  'Main' => array(
    'Home' => '@homepage',
    'Browse Plugins' => '@plugins',
    'Categories' => '@plugin_categories',
    'Browse Developers' => '@authors',
    'Lists' => '@community_lists',
  ),
  'Footer' => array(
    'Home' => '/',
    'About SympLIST' => '@about',
    'Feedback' => '@contact',
    'Contact' => 'http://symplist.lighthouseapp.com/projects/36266-symplist/tickets/new',
  ),
);
$settings = array(
  'database' => array(
    'driven' => '1',
  ),
);

