<?php
// auto-generated by sfViewConfigHandler
// date: 2009/11/13 16:16:35
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('text.css', '', array ());
  $response->addStylesheet('960.css', '', array ());
  $response->addStylesheet('custom.css', '', array ());
  $response->addStylesheet('jquery.autocomplete.css', '', array ());
  $response->addJavascript('http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js', '', array ());
  $response->addJavascript('jquery.infieldlabel.min.js', '', array ());
  $response->addJavascript('jquery.rating.pack.js', '', array ());
  $response->addJavascript('jquery.autocomplete.js', '', array ());
  $response->addJavascript('theme.js', '', array ());


