<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommunityList extends BaseCommunityList
{
  public function getOrderedItems()
  {
    return Doctrine::getTable('CommunityListItem')
          ->createQuery('i')
          ->orderBy('i.score DESC, i.created_at DESC')
          ->where('i.list_id = ?', $this['id'])
          ->execute();
  }
}