<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommunityListTable extends Doctrine_Table
{
  public function getPopularListsQuery()
  {
    $q = $this->createQuery('l')
             ->select('l.*, SUM(i.score) as total_score')
             ->innerJoin('l.Items i')
             ->groupBy('i.list_id')
             ->orderBy('l.featured, total_score DESC')
    ;

    return $q;
  }
}