<?php

/**
 * PluginCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5925 2009-06-22 21:27:17Z jwage $
 */
class PluginCategory extends BasePluginCategory
{
  public function getRoute()
  {
    return '@plugins_by_category?slug='.$this['slug'];
  }
}