<?php

/**
 * SymfonyPlugin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5925 2009-06-22 21:27:17Z jwage $
 */
class SymfonyPlugin extends BaseSymfonyPlugin
{
  public function getRoute()
  {
    return '@plugin?title='.$this['title'];
  }
  
  public function getRating()
  {
    $q = Doctrine::getTable('Comment')->createQuery('c')
              ->select('AVG(c.rating) as average')
              ->innerJoin('c.SymfonyPluginComment pc')
              ->where('pc.id = ?', $this['id']);

    $result = $q->fetchOne();

    return $result['average'];
  }
  
  public function getSymfonyPluginsUrl()
  {
    return 'http://www.symfony-project.com/plugins/'.$this['title'];
  }
}