<?php

/**
 * sfSettingsConfigHandler 
 * Parses the defaults.yml file in order to load any defaults the user wishes to
 * pre-load in the execution filter (if used)
 * 
 * @uses sfYamlConfigHandler
 * @package 
 * @version $id$
 * @copyright 2006-2007 Chris Wage
 * @author Chris Wage <cwage@centresource.com> 
 * @license See LICENSE that came packaged with this software
 */
class sfSettingsConfigHandler extends sfYamlConfigHandler
{
  /**
   * execute 
	* Execute the filter and return code to be executed
   * 
   * @param mixed $configFiles 
   * @access public
   * @return string
   */
  public function execute($configFiles)
  { 
    // Parse yaml config files
   $configs = $this->parseYamls($configFiles);
	 $data = array();
	 if(isset($configs['settings']))
	 {
			foreach ($configs['settings'] as $setting) {
				$data[] = "\$default_settings[] = \"$setting\";";
			 }

		    // compile data
		    $retval = sprintf("<?php\n" .
		    "// auto-generated by sfSettingsConfigHandler\n" .
		    "// date: %s\n%s\n", date('Y-m-d H:i:s'), implode("\n", $data));

		    return $retval;
	  } 
	 

  }

}

?>
