<?php

/**
 * csNavigationConfigHandler 
 * Parses the navigation.yml file in order to load the site navigation
 * Borrows heavily from sfSettingsConfigHandler by Chris Wage
 *
 * @uses sfYamlConfigHandler
 * @package 
 * @version $id$
 * @copyright 2006-2007 Brent Shaffer
 * @author Brent Shaffer <bshaffer@centresource.com> 
 * @license See LICENSE that came packaged with this software
 */
class csNavigationConfigHandler extends sfYamlConfigHandler
{
  /**
   * execute 
	* Execute the filter and return code to be executed
   * 
   * @param mixed $configFiles 
   * @access public
   * @return string
   */
  public function execute($configFiles)
  { 
    // Parse yaml config files
    $configs = $this->parseYamls($configFiles);
	 $data = array();

	 $navigation = isset($configs['navigation']) ? $configs['navigation'] : array();
	 $settings = isset($configs['settings']) ? $configs['settings'] : array();
	 $data_str = "\$navigation = ". $this->dataArray($navigation) . ";\n";
	 $data_str .= "\$settings = ". $this->dataArray($settings) . ";\n";
    // compile data
    $retval = sprintf("<?php\n" .
    "// auto-generated by csNavigationConfigHandler\n" .
    "// date: %s\n%s\n", date('Y-m-d H:i:s'), $data_str); //implode("\n", $data));

    return $retval;
  }
	public function dataArray($arr, $level = 0)
	{
		$data_arr = array();
		$data_arr[] = "array(";
		foreach ($arr as $key => $route)
    {
			if(is_array($route))
			{

					$data_arr[] = sprintf(str_repeat('  ', $level)."  '%s' => %s,", $key, str_replace('\\', '\\\\', $this->dataArray($route, $level + 1)));
		
			}
			else
			{
				$data_arr[] = sprintf(str_repeat('  ', $level)."  '%s' => '%s',", $key, str_replace('\\', '\\\\', $route));
			}
		}
		$data_arr[] = str_repeat('  ', $level).")";
		return implode("\n", $data_arr);
	}

}

?>
