<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginModelAttachment extends BaseModelAttachment
{
  public function getAttachmentRoute()
  {
    return $this->getUrl();
  }
}