<?php

/**
 * BaseDocumentAttachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseDocumentAttachment extends Attachment
{
    public function setUp()
    {
        parent::setUp();
        
    }
}