<?php

/**
 * BaseAttachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $description
 * @property string $url
 * @property enum $type
 * @property integer $object_id
 * @property string $object_class
 * 
 * @method string     getTitle()        Returns the current record's "title" value
 * @method clob       getDescription()  Returns the current record's "description" value
 * @method string     getUrl()          Returns the current record's "url" value
 * @method enum       getType()         Returns the current record's "type" value
 * @method integer    getObjectId()     Returns the current record's "object_id" value
 * @method string     getObjectClass()  Returns the current record's "object_class" value
 * @method Attachment setTitle()        Sets the current record's "title" value
 * @method Attachment setDescription()  Sets the current record's "description" value
 * @method Attachment setUrl()          Sets the current record's "url" value
 * @method Attachment setType()         Sets the current record's "type" value
 * @method Attachment setObjectId()     Sets the current record's "object_id" value
 * @method Attachment setObjectClass()  Sets the current record's "object_class" value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BaseAttachment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('attachment');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'image',
              1 => 'video',
              2 => 'audio',
              3 => 'document',
              4 => 'application',
              5 => 'link',
              6 => 'model',
              7 => 'custom',
              8 => 'other',
             ),
             'default' => 'other',
             ));
        $this->hasColumn('object_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('object_class', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->setSubClasses(array(
             'ImageAttachment' => 
             array(
              'type' => 'image',
             ),
             'VideoAttachment' => 
             array(
              'type' => 'video',
             ),
             'AudioAttachment' => 
             array(
              'type' => 'audio',
             ),
             'DocumentAttachment' => 
             array(
              'type' => 'document',
             ),
             'ApplicationAttachment' => 
             array(
              'type' => 'application',
             ),
             'ModelAttachment' => 
             array(
              'type' => 'model',
             ),
             'LinkAttachment' => 
             array(
              'type' => 'link',
             ),
             'CustomAttachment' => 
             array(
              'type' => 'custom',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}