<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginCommenter extends BaseCommenter
{
 public function getName()
 {
   return $this['username'];
 }
}