<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCommentTable extends Doctrine_Table
{

   public function approveAll()
   {
   	$query = $this->createQuery()->update()->set('approved', 1);
   	return $query->execute();
   }

  public function findApproved()
  {    
    $query = $this->createQuery('co')
                  ->addWhere('co.approved', true);

    return $query->execute();
  }

  public function getApprovedQuery(&$query)
  {    
    $query->addWhere($query->getRootAlias().'.approved = ?', true);

    return $query;
  }

  public function findUnapproved()
  {    
    $query = $this->createQuery('co')
                  ->addWhere('co.approved = false');

    return $query->execute();
  }

  public function findApprovedBy($user)
  {    
    $query = $this->createQuery('co')
                            ->addWhere('co.approved_by = ?', true);

    return $query->execute();
  }

}