<?php

/**
 * BasesfSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $type
 * @property string $options
 * @property clob $value
 * 
 * @method integer   getId()      Returns the current record's "id" value
 * @method string    getName()    Returns the current record's "name" value
 * @method string    getType()    Returns the current record's "type" value
 * @method string    getOptions() Returns the current record's "options" value
 * @method clob      getValue()   Returns the current record's "value" value
 * @method sfSetting setId()      Sets the current record's "id" value
 * @method sfSetting setName()    Sets the current record's "name" value
 * @method sfSetting setType()    Sets the current record's "type" value
 * @method sfSetting setOptions() Sets the current record's "options" value
 * @method sfSetting setValue()   Sets the current record's "value" value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class BasesfSetting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_setting');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('options', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('value', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}