<?php
// auto-generated by sfRoutingConfigHandler
// date: 2009/08/07 11:39:53
return array(
'meta_data_edit' => new sfRoute('/seo/meta_data/edit', array (
  'module' => 'csSEO',
  'action' => 'editMetaData',
), array (
), array (
)),
'sitemap_xml_edit' => new sfRoute('/seo/sitemap_data/edit', array (
  'module' => 'csSEO',
  'action' => 'editSitemapData',
), array (
), array (
)),
'sitemap_xml' => new sfRoute('/sitemap.xml', array (
  'module' => 'csSEO',
  'action' => 'sitemap',
  'location_slug' => 'main',
  'format' => 'xml',
), array (
), array (
)),
'jsthumbnail' => new sfRoute('/jsThumbnail', array (
  'module' => 'jsThumbnail',
  'action' => 'thumbnail',
), array (
), array (
)),
'jsthumbnail_remote' => new sfRoute('/jsThumbnail/remote', array (
  'module' => 'jsThumbnail',
  'action' => 'remote',
), array (
), array (
)),
'cscomments_comments_add' => new sfRoute('/csComments/comments/add', array (
  'module' => 'csComments',
  'action' => 'add',
), array (
), array (
)),
'cscomments_comments_do_add' => new sfRoute('/csComments/comments/addComment', array (
  'module' => 'csComments',
  'action' => 'doAdd',
), array (
), array (
)),
'cscomments_comments_edit' => new sfRoute('/csComments/comments/editComment', array (
  'module' => 'csComments',
  'action' => 'doEdit',
), array (
), array (
)),
'cscomments_comments_delete' => new sfRoute('/csComments/comments/deleteComment', array (
  'module' => 'csComments',
  'action' => 'doDelete',
), array (
), array (
)),
'comment_csCommentAdmin' => new sfDoctrineRouteCollection(array (
  'model' => 'Comment',
  'module' => 'csCommentAdmin',
  'prefix_path' => 'csCommentAdmin',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'comment_csCommentAdmin',
  'requirements' => 
  array (
  ),
)),
'post_post' => new sfDoctrineRouteCollection(array (
  'model' => 'Post',
  'module' => 'post',
  'prefix_path' => 'post',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'post_post',
  'requirements' => 
  array (
  ),
)),
'page_page' => new sfDoctrineRouteCollection(array (
  'model' => 'Page',
  'module' => 'page',
  'prefix_path' => 'page',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'page_page',
  'requirements' => 
  array (
  ),
)),
'homepage' => new sfRoute('/', array (
  'module' => 'default',
  'action' => 'index',
), array (
), array (
)),
'sf_guard_signin' => new sfRoute('/login', array (
  'module' => 'sfGuardAuth',
  'action' => 'signin',
), array (
), array (
)),
'sf_guard_signout' => new sfRoute('/logout', array (
  'module' => 'sfGuardAuth',
  'action' => 'signout',
), array (
), array (
)),
'sf_guard_password' => new sfRoute('/request_password', array (
  'module' => 'sfGuardAuth',
  'action' => 'password',
), array (
), array (
)),
'default_index' => new sfRoute('/login', array (
  'module' => 'sfGuardAuth',
  'action' => 'signin',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
