<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addattachment extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('attachment', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'url' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'image',
              1 => 'video',
              2 => 'audio',
              3 => 'document',
              4 => 'application',
              5 => 'link',
              6 => 'model',
              7 => 'custom',
              8 => 'other',
              ),
              'default' => 'other',
              'length' => NULL,
             ),
             'object_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'object_class' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
              'attachment_type' => 
              array(
              'fields' => 
              array(
               0 => 'type',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('attachment');
    }
}