<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addSymfonyPluginFieldsForApiMigration extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('plugin_release_symfony_api_version', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'release_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'api_version_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('symfony_api_version', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '5',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addColumn('symfony_plugin', 'symplist_index', 'decimal', '3', array(
             'scale' => '1',
             ));
    }

    public function down()
    {
        $this->dropTable('plugin_release_symfony_api_version');
        $this->dropTable('symfony_api_version');
        $this->removeColumn('symfony_plugin', 'symplist_index');
    }
}