<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addManyUsersToPluginIndexMigration extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('symfony_plugin', 'symfony_plugin_user_id_sf_guard_user_id');
        $this->createForeignKey('symfony_plugin_author', 'symfony_plugin_author_plugin_id_symfony_plugin_id', array(
             'name' => 'symfony_plugin_author_plugin_id_symfony_plugin_id',
             'local' => 'plugin_id',
             'foreign' => 'id',
             'foreignTable' => 'symfony_plugin',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('symfony_plugin_author', 'symfony_plugin_author_author_id_sf_guard_user_id', array(
             'name' => 'symfony_plugin_author_author_id_sf_guard_user_id',
             'local' => 'author_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('symfony_plugin_author', 'symfony_plugin_author_symfony_plugin_id_symfony_plugin_id', array(
             'name' => 'symfony_plugin_author_symfony_plugin_id_symfony_plugin_id',
             'local' => 'symfony_plugin_id',
             'foreign' => 'id',
             'foreignTable' => 'symfony_plugin',
             ));
        $this->addIndex('symfony_plugin_author', 'symfony_plugin_author_plugin_id', array(
             'fields' => 
             array(
              0 => 'plugin_id',
             ),
             ));
        $this->addIndex('symfony_plugin_author', 'symfony_plugin_author_author_id', array(
             'fields' => 
             array(
              0 => 'author_id',
             ),
             ));
        $this->addIndex('symfony_plugin_author', 'symfony_plugin_author_symfony_plugin_id', array(
             'fields' => 
             array(
              0 => 'symfony_plugin_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('symfony_plugin', 'symfony_plugin_user_id_sf_guard_user_id', array(
             'name' => 'symfony_plugin_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->dropForeignKey('symfony_plugin_author', 'symfony_plugin_author_plugin_id_symfony_plugin_id');
        $this->dropForeignKey('symfony_plugin_author', 'symfony_plugin_author_author_id_sf_guard_user_id');
        $this->dropForeignKey('symfony_plugin_author', 'symfony_plugin_author_symfony_plugin_id_symfony_plugin_id');
        $this->removeIndex('symfony_plugin_author', 'symfony_plugin_author_plugin_id', array(
             'fields' => 
             array(
              0 => 'plugin_id',
             ),
             ));
        $this->removeIndex('symfony_plugin_author', 'symfony_plugin_author_author_id', array(
             'fields' => 
             array(
              0 => 'author_id',
             ),
             ));
        $this->removeIndex('symfony_plugin_author', 'symfony_plugin_author_symfony_plugin_id', array(
             'fields' => 
             array(
              0 => 'symfony_plugin_id',
             ),
             ));
    }
}