<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('plugin_release', 'dependencies');
    }

    public function down()
    {
        $this->addColumn('plugin_release', 'dependencies', 'string', '255', array());
    }
}