<?php
// auto-generated by csNavigationConfigHandler
// date: 2009-08-18 03:30:48
$navigation = array(
  'Main' => array(
    'Home' => '@homepage',
    'Plugins' => '@plugins',
    'Categories' => '@plugin_categories',
    'Developers' => '@authors',
  ),
  'Footer' => array(
    'home' => '/',
    'about' => '@about',
    'contact' => '@contact',
  ),
);
$settings = array(
  'database' => array(
    'driven' => '1',
  ),
);

