<?php
// auto-generated by csNavigationConfigHandler
// date: 2009-08-11 17:37:34
$navigation = array(
  'Main' => array(
    'Home' => '@homepage',
    'Plugins' => '@plugins',
    'Categories' => '@plugin_categories',
    'Developers' => array(
      '~route' => '@authors',
      'create' => '@author_new',
    ),
  ),
  'Footer' => array(
    'home' => '/',
    'about' => '@about',
    'contact' => '@contact',
  ),
);
$settings = array(
  'database' => array(
    'driven' => '1',
  ),
);

