<?php
// auto-generated by csNavigationConfigHandler
// date: 2009-08-07 09:59:53
$navigation = array(
  'Main' => array(
    'Plugins' => '@plugins',
    'Categories' => '@plugin_categories',
    'Developers' => '@authors',
  ),
);
$settings = array(
  'database' => array(
    'driven' => '1',
  ),
);

