<?php
// auto-generated by csNavigationConfigHandler
// date: 2009-08-07 11:01:48
$navigation = array(
  'Main' => array(
    'Plugins' => '@homepage',
    'Categories' => '@plugin_categories',
    'Developers' => '@authors',
  ),
  'Footer' => array(
    'home' => '/',
    'about' => '/about',
    'contact' => '/contact',
  ),
);
$settings = array(
  'database' => array(
    'driven' => '1',
  ),
);

