<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/08/11 15:16:49

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'classname' => 'DoctrinePDO',
  'dsn' => 'mysql:dbname=symplist;host=localhost',
  'username' => 'root',
  'password' => NULL,
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'doctrine',
)),);
