<?php

/**
 * BaseSeoPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $title
 * @property clob $description
 * @property string $keywords
 * @property decimal $priority
 * @property enum $changeFreq
 * @property boolean $exclude_from_sitemap
 * 
 * @method string  getUrl()                  Returns the current record's "url" value
 * @method string  getTitle()                Returns the current record's "title" value
 * @method clob    getDescription()          Returns the current record's "description" value
 * @method string  getKeywords()             Returns the current record's "keywords" value
 * @method decimal getPriority()             Returns the current record's "priority" value
 * @method enum    getChangeFreq()           Returns the current record's "changeFreq" value
 * @method boolean getExcludeFromSitemap()   Returns the current record's "exclude_from_sitemap" value
 * @method SeoPage setUrl()                  Sets the current record's "url" value
 * @method SeoPage setTitle()                Sets the current record's "title" value
 * @method SeoPage setDescription()          Sets the current record's "description" value
 * @method SeoPage setKeywords()             Sets the current record's "keywords" value
 * @method SeoPage setPriority()             Sets the current record's "priority" value
 * @method SeoPage setChangeFreq()           Sets the current record's "changeFreq" value
 * @method SeoPage setExcludeFromSitemap()   Sets the current record's "exclude_from_sitemap" value
 * 
 * @package    plugintracker
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeoPage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seo_page');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('priority', 'decimal', null, array(
             'type' => 'decimal',
             'default' => 0.5,
             'scale' => 1,
             ));
        $this->hasColumn('changeFreq', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'always',
              1 => 'hourly',
              2 => 'daily',
              3 => 'weekly',
              4 => 'monthly',
              5 => 'yearly',
              6 => 'never',
             ),
             'default' => 'weekly',
             ));
        $this->hasColumn('exclude_from_sitemap', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}