<?php

/**
 * BaseCommenter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $username
 * @property string $email
 * @property string $website
 * @property Comment $Comment
 * 
 * @method string    getUsername() Returns the current record's "username" value
 * @method string    getEmail()    Returns the current record's "email" value
 * @method string    getWebsite()  Returns the current record's "website" value
 * @method Comment   getComment()  Returns the current record's "Comment" value
 * @method Commenter setUsername() Sets the current record's "username" value
 * @method Commenter setEmail()    Sets the current record's "email" value
 * @method Commenter setWebsite()  Sets the current record's "website" value
 * @method Commenter setComment()  Sets the current record's "Comment" value
 * 
 * @package    plugintracker
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCommenter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('commenter');
        $this->hasColumn('username', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('website', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Comment', array(
             'local' => 'id',
             'foreign' => 'user_id'));
    }
}