<?php

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property clob $body
 * @property boolean $approved
 * @property timestamp $approved_at
 * @property integer $user_id
 * @property Commenter $Commenter
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method clob      getBody()        Returns the current record's "body" value
 * @method boolean   getApproved()    Returns the current record's "approved" value
 * @method timestamp getApprovedAt()  Returns the current record's "approved_at" value
 * @method integer   getUserId()      Returns the current record's "user_id" value
 * @method Commenter getCommenter()   Returns the current record's "Commenter" value
 * @method Comment   setId()          Sets the current record's "id" value
 * @method Comment   setBody()        Sets the current record's "body" value
 * @method Comment   setApproved()    Sets the current record's "approved" value
 * @method Comment   setApprovedAt()  Sets the current record's "approved_at" value
 * @method Comment   setUserId()      Sets the current record's "user_id" value
 * @method Comment   setCommenter()   Sets the current record's "Commenter" value
 * 
 * @package    plugintracker
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('approved', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('approved_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Commenter', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($nestedset0);
        $this->actAs($timestampable0);
    }
}