<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasecsNavigationMenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cs_navigation_menu');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('root_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        $this->hasOne('csNavigationItem as NavigationRoot', array(
             'local' => 'root_id',
             'foreign' => 'id'));
    }
}